import { Category, Meal } from './types';

export const mockCategories: Category[] = [
  {
    strCategory: 'Beef',
  },
  {
    strCategory: 'Breakfast',
  },
  {
    strCategory: 'Chicken',
  },
  {
    strCategory: 'Dessert',
  },
  {
    strCategory: 'Goat',
  },
  {
    strCategory: 'Lamb',
  },
  {
    strCategory: 'Miscellaneous',
  },
  {
    strCategory: 'Pasta',
  },
  {
    strCategory: 'Pork',
  },
  {
    strCategory: 'Seafood',
  },
  {
    strCategory: 'Side',
  },
  {
    strCategory: 'Starter',
  },
  {
    strCategory: 'Vegan',
  },
  {
    strCategory: 'Vegetarian',
  },
];

export const mockMeals: Meal[] = [
  {
    idMeal: '52959',
    strMeal: 'Baked salmon with fennel & tomatoes',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'British',
    strInstructions:
      'Heat oven to 180C/fan 160C/gas 4. Trim the fronds from the fennel and set aside. Cut the fennel bulbs in half, then cut each half into 3 wedges. Cook in boiling salted water for 10 mins, then drain well. Chop the fennel fronds roughly, then mix with the parsley and lemon zest.\r\n\r\nSpread the drained fennel over a shallow ovenproof dish, then add the tomatoes. Drizzle with olive oil, then bake for 10 mins. Nestle the salmon among the veg, sprinkle with lemon juice, then bake 15 mins more until the fish is just cooked. Scatter over the parsley and serve.',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1548772327.jpg',
    strTags: 'Paleo,Keto,HighFat,Baking,LowCarbs',
    strYoutube: 'https://www.youtube.com/watch?v=xvPR2Tfw5k0',
    strIngredient1: 'Fennel',
    strIngredient2: 'Parsley',
    strIngredient3: 'Lemon',
    strIngredient4: 'Cherry Tomatoes',
    strIngredient5: 'Olive Oil',
    strIngredient6: 'Salmon',
    strIngredient7: 'Black Olives',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2 medium',
    strMeasure2: '2 tbs chopped',
    strMeasure3: 'Juice of 1',
    strMeasure4: '175g',
    strMeasure5: '1 tbs',
    strMeasure6: '350g',
    strMeasure7: 'to serve',
    strMeasure8: '',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource:
      'https://www.bbcgoodfood.com/recipes/7745/baked-salmon-with-fennel-and-tomatoes',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52819',
    strMeal: 'Cajun spiced fish tacos',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Mexican',
    strInstructions:
      "Cooking in a cajun spice and cayenne pepper marinade makes this fish super succulent and flavoursome. Top with a zesty dressing and serve in a tortilla for a quick, fuss-free main that's delightfully summery.\r\n\r\nOn a large plate, mix the cajun spice and cayenne pepper with a little seasoning and use to coat the fish all over.\r\n\r\nHeat a little oil in a frying pan, add in the fish and cook over a medium heat until golden. Reduce the heat and continue frying until the fish is cooked through, about 10 minutes. Cook in batches if you don’t have enough room in the pan.\r\n\r\nMeanwhile, prepare the dressing by combining all the ingredients with a little seasoning.\r\nSoften the tortillas by heating in the microwave for 5-10 seconds. Pile high with the avocado, lettuce and spring onion, add a spoonful of salsa, top with large flakes of fish and drizzle over the dressing.",
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg',
    strTags: 'Spicy,Fish',
    strYoutube: 'https://www.youtube.com/watch?v=N4EdUt0Ou48',
    strIngredient1: 'cajun',
    strIngredient2: 'cayenne pepper',
    strIngredient3: 'white fish',
    strIngredient4: 'vegetable oil',
    strIngredient5: 'flour tortilla',
    strIngredient6: 'avocado',
    strIngredient7: 'little gem lettuce',
    strIngredient8: 'spring onion',
    strIngredient9: 'salsa',
    strIngredient10: 'sour cream',
    strIngredient11: 'lemon',
    strIngredient12: 'garlic',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2 tbsp',
    strMeasure2: '1 tsp',
    strMeasure3: '4 fillets',
    strMeasure4: '1 tsp',
    strMeasure5: '8',
    strMeasure6: '1 sliced',
    strMeasure7: '2 shredded',
    strMeasure8: '4 shredded',
    strMeasure9: '1 x 300ml',
    strMeasure10: '1 pot',
    strMeasure11: '1',
    strMeasure12: '1 clove finely chopped',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource:
      'https://realfood.tesco.com/recipes/cajun-spiced-fish-tacos.html',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52944',
    strMeal: 'Escovitch Fish',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Jamaican',
    strInstructions:
      'Rinse fish; rub with lemon or lime, seasoned with salt and pepper or use your favorite seasoning. I used creole seasoning. Set aside or place in the oven to keep it warm until sauce is ready.\r\n\r\nIn large skillet heat oil over medium heat, until hot, add the fish, cook each side- for about 5-7 minutes until cooked through and crispy on both sides. Remove fish and set aside. Drain oil and leave about 2-3 tablespoons of oil\r\nAdd, bay leave, garlic and ginger, stir-fry for about a minute making sure the garlic does not burn\r\nThen add onion, bell peppers, thyme, scotch bonnet, sugar, all spice-continue stirring for about 2-3 minutes. Add vinegar, mix an adjust salt and pepper according to preference. Let it simmer for about 2 more minutes. \r\n\r\nDiscard bay leave, thyme spring and serve over fish with a side of this bammy. You may make the sauce about 2 days in advance.',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1520084413.jpg',
    strTags: 'Seafood,Spicy,Speciality,Easter',
    strYoutube: 'https://www.youtube.com/watch?v=nF6DOtGE6k8',
    strIngredient1: 'Red Snapper',
    strIngredient2: 'Vegetable Oil',
    strIngredient3: 'Garlic',
    strIngredient4: 'Ginger',
    strIngredient5: 'Thyme',
    strIngredient6: 'Bay Leaf',
    strIngredient7: 'Red Pepper',
    strIngredient8: 'Yellow Pepper',
    strIngredient9: 'Onion',
    strIngredient10: 'Carrots',
    strIngredient11: 'Sugar',
    strIngredient12: 'Allspice',
    strIngredient13: 'Worcestershire Sauce',
    strIngredient14: 'Scotch Bonnet',
    strIngredient15: 'Lime',
    strIngredient16: 'Malt Vinegar',
    strIngredient17: 'Pepper',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2 Pounds',
    strMeasure2: '1/2 cup ',
    strMeasure3: '1 clove peeled crushed',
    strMeasure4: '1/2 tsp',
    strMeasure5: '2 sprigs',
    strMeasure6: '1',
    strMeasure7: '0.5',
    strMeasure8: '0.5',
    strMeasure9: '1 sliced',
    strMeasure10: '1 chopped',
    strMeasure11: '1 tbs',
    strMeasure12: '1/2 tsp',
    strMeasure13: '1 tsp ',
    strMeasure14: '1',
    strMeasure15: '1',
    strMeasure16: '3/4 cup ',
    strMeasure17: 'pinch',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.africanbites.com/jamaican-escovitched-fish/',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '53043',
    strMeal: 'Fish fofos',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Portuguese',
    strInstructions:
      'STEP 1\r\n\r\nPut the fish into a lidded pan and pour over enough water to cover. Bring to a simmer and gently poach for 10 minutes over a low heat with the lid on. Drain and flake the fish.\r\n\r\nSTEP 2\r\n\r\nPut the fish, potato, green chilli, coriander, cumin, black pepper, garlic and ginger in a large bowl. Season, add the rice flour, mix well and break in 1 egg. Stir the mixture and divide into 15, then form into small logs. Break the remaining eggs into a bowl and whisk lightly. Put the breadcrumbs into another bowl. Dip each fofo in the beaten egg followed by the breadcrumb mixture. Chill for 20 minutes.\r\n\r\nSTEP 3\r\n\r\nHeat 1cm of oil in a large frying pan over a medium heat. Fry the fofos in batches for 2 minutes on each side, turning gently to get an even golden brown colour all over. Drain on kitchen paper and repeat with the remaining fofos.\r\n\r\nSTEP 4\r\n\r\nFor the onion salad, mix together the onion, coriander and lemon juice with a pinch of salt. Serve with the fofos and mango chutney.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/a15wsa1614349126.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=YXUZHK2PrV8',
    strIngredient1: 'Haddock',
    strIngredient2: 'Potatoes',
    strIngredient3: 'Green Chilli',
    strIngredient4: 'Coriander',
    strIngredient5: 'Cumin Seeds',
    strIngredient6: 'Pepper',
    strIngredient7: 'Garlic',
    strIngredient8: 'Ginger',
    strIngredient9: 'Flour',
    strIngredient10: 'Eggs',
    strIngredient11: 'Breadcrumbs',
    strIngredient12: 'Vegetable Oil',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '600g',
    strMeasure2: '300g',
    strMeasure3: '1 chopped',
    strMeasure4: '3 tbs',
    strMeasure5: '1 tsp ',
    strMeasure6: '1/2 tsp',
    strMeasure7: '3 cloves',
    strMeasure8: '2 pieces ',
    strMeasure9: '2 tbs',
    strMeasure10: '3',
    strMeasure11: '75g',
    strMeasure12: 'For frying',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.olivemagazine.com/recipes/fish-and-seafood/fish-fofos/',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52802',
    strMeal: 'Fish pie',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'British',
    strInstructions:
      '01.Put the potatoes in a large pan of cold salted water and bring to the boil. Lower the heat, cover, then simmer gently for 15 minutes until tender. Drain, then return to the pan over a low heat for 30 seconds to drive off any excess water. Mash with 1 tbsp olive oil, then season.\r\n02.Meanwhile put the milk in a large sauté pan, add the fish and bring to the boil. Remove from the heat, cover and stand for 3 minutes. Remove the fish (reserving the milk) and pat dry with kitchen paper, then gently flake into an ovenproof dish, discarding the skin and any bones.\r\n03.Heat the remaining oil in a pan, stir in the flour and cook for 30 seconds. Gradually stir in 200-250ml of the reserved milk (discard the rest). Grate in nutmeg, season, then bubble until thick. Stir in the cream.\r\n04.Preheat the oven to 190°C/fan170°C/gas 5. Grate the artichokes and add to the dish with the leek, prawns and herbs. Stir the lemon zest and juice into the sauce, then pour over. Mix gently with a wooden spoon.\r\n05.Spoon the mash onto the fish mixture, then use a fork to make peaks, which will crisp and brown as it cooks. Sprinkle over the cheese, then bake for 35-40 minutes until golden and bubbling. Serve with wilted greens.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg',
    strTags: 'Fish,Pie,Breakfast,Baking',
    strYoutube: 'https://www.youtube.com/watch?v=2sX4fCgg-UI',
    strIngredient1: 'Floury Potatoes',
    strIngredient2: 'Olive Oil',
    strIngredient3: 'Semi-skimmed Milk',
    strIngredient4: 'White Fish Fillets',
    strIngredient5: 'Plain flour',
    strIngredient6: 'Nutmeg',
    strIngredient7: 'Double Cream',
    strIngredient8: 'Jerusalem Artichokes',
    strIngredient9: 'Leek',
    strIngredient10: 'Prawns',
    strIngredient11: 'Parsley',
    strIngredient12: 'Dill',
    strIngredient13: 'Lemon',
    strIngredient14: 'Gruyère',
    strIngredient15: 'Lemon',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '900g',
    strMeasure2: '2 tbsp',
    strMeasure3: '600ml',
    strMeasure4: '800g',
    strMeasure5: '1 tbsp',
    strMeasure6: 'Grating',
    strMeasure7: '3 tbsp',
    strMeasure8: '200g',
    strMeasure9: '1 finely sliced',
    strMeasure10: '200g peeled raw',
    strMeasure11: 'Large handful',
    strMeasure12: 'Handful',
    strMeasure13: 'Grated zest of 1',
    strMeasure14: '25g grated',
    strMeasure15: 'Juice of 1',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: '',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52918',
    strMeal: 'Fish Stew with Rouille',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'French',
    strInstructions:
      'Twist the heads from the prawns, then peel away the legs and shells, but leave the tails intact. Devein each prawn. Fry the shells in 1 tbsp oil for 5 mins, until dark pink and golden in patches. Add the wine, boil down by two thirds, then pour in the stock. Strain into a jug, discarding the shells.\r\nHeat the rest of the oil in a deep frying pan or casserole. Add the fennel, onion and garlic, season, then cover and gently cook for 10 mins until softened. Meanwhile, peel the potato and cut into 2cm-ish chunks. Put into a pan of cold water, bring to the boil and cook for 5 mins until almost tender. Drain in a colander.\r\nPeel a strip of zest from the orange. Put the zest, star anise, bay and ½ tsp harissa into the pan. Fry gently, uncovered, for 5-10 mins, until the vegetables are soft, sweet and golden.\r\nStir in the tomato purée, cook for 2 mins, then add the tomatoes and stock. Simmer for 10 mins until the sauce thickens slightly. Season to taste. The sauce can be made ahead, then reheated later in the day. Meantime, scrub the mussels or clams and pull away any stringy beards. Any that are open should be tapped sharply on the worktop – if they don’t close after a few seconds, discard them.\r\nReheat the sauce if necessary, then stir the potato, chunks of fish and prawns very gently into the stew. Bring back to the boil, then cover and gently simmer for 3 mins. Scatter the mussels or clams over the stew, then cover and cook for 2 mins more or until the shells have opened wide. Discard any that remain closed. The chunks of fish should flake easily and the prawns should be pink through. Scatter with the thyme leaves.\r\nTo make the quick rouille, stir the rest of the harissa through the mayonnaise. Serve the stew in bowls, topped with spoonfuls of rouille, which will melt into the sauce and enrich it. Have some good bread ready, as you’ll definitely want to mop up the juices.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/vptqpw1511798500.jpg',
    strTags: 'Fish,Seafood,Shellfish',
    strYoutube: 'https://www.youtube.com/watch?v=fp9Lqx2EUco',
    strIngredient1: 'Prawns',
    strIngredient2: 'Olive Oil',
    strIngredient3: 'Dry White Wine',
    strIngredient4: 'Fish Stock',
    strIngredient5: 'Fennel',
    strIngredient6: 'Onion',
    strIngredient7: 'Garlic',
    strIngredient8: 'Potatoes',
    strIngredient9: 'Orange',
    strIngredient10: 'Star Anise',
    strIngredient11: 'Bay Leaf',
    strIngredient12: 'Harissa Spice',
    strIngredient13: 'Tomato Puree',
    strIngredient14: 'Chopped Tomatoes',
    strIngredient15: 'Mussels',
    strIngredient16: 'White Fish',
    strIngredient17: 'Thyme',
    strIngredient18: 'Bread',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '6 large',
    strMeasure2: '3 tbs',
    strMeasure3: '150ml',
    strMeasure4: '200ml',
    strMeasure5: '1 small finely diced',
    strMeasure6: '1 small finely diced',
    strMeasure7: '3 cloves Chopped',
    strMeasure8: '1 large',
    strMeasure9: '1',
    strMeasure10: '1',
    strMeasure11: '1',
    strMeasure12: '1 1/2 tsp ',
    strMeasure13: '2 tbs',
    strMeasure14: '400g',
    strMeasure15: 'Handful',
    strMeasure16: '200g',
    strMeasure17: '2',
    strMeasure18: 'to serve',
    strMeasure19: '',
    strMeasure20: '',
    strSource:
      'https://www.bbcgoodfood.com/recipes/532640/summer-fish-stew-with-rouille',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52764',
    strMeal: 'Garides Saganaki',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Greek',
    strInstructions:
      'Place the prawns in a pot and add enough water to cover. Boil for 5 minutes. Drain, reserving the liquid, and set aside.\r\nHeat 2 tablespoons of oil in a saucepan. Add the onion; cook and stir until soft. Mix in the parsley, wine, tomatoes, garlic and remaining olive oil. Simmer, stirring occasionally, for about 30 minutes, or until the sauce is thickened.\r\nWhile the sauce is simmering, the prawns should become cool enough to handle. First remove the legs by pinching them, and then pull off the shells, leaving the head and tail on.\r\nWhen the sauce has thickened, stir in the prawns. Bring to a simmer again if the sauce has cooled with the prawns, and cook for about 5 minutes. Add the feta and remove from the heat. Let stand until the cheese starts to melt. Serve warm with slices of crusty bread.\r\nThough completely untraditional, you can add a few tablespoons of stock or passata to this recipe to make a delicious pasta sauce. Toss with pasta after adding the feta, and serve.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg',
    strTags: 'Seafood,Shellfish',
    strYoutube: 'https://www.youtube.com/watch?v=uO0ejc85zSE',
    strIngredient1: 'Raw king prawns',
    strIngredient2: 'Olive oil',
    strIngredient3: 'Chopped onion',
    strIngredient4: 'Freshly chopped parsley',
    strIngredient5: 'White wine',
    strIngredient6: 'Chopped tomatoes',
    strIngredient7: 'Minced garlic',
    strIngredient8: 'Cubed Feta cheese',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: undefined,
    strIngredient17: undefined,
    strIngredient18: undefined,
    strIngredient19: undefined,
    strIngredient20: undefined,
    strMeasure1: '500g',
    strMeasure2: '3 tablespoons',
    strMeasure3: '1',
    strMeasure4: 'pinch',
    strMeasure5: '250ml',
    strMeasure6: '1 (400g) tin',
    strMeasure7: '1/2 teaspoon',
    strMeasure8: '1 (200g) pack',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: undefined,
    strMeasure17: undefined,
    strMeasure18: undefined,
    strMeasure19: undefined,
    strMeasure20: undefined,
    strSource: undefined,
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '53041',
    strMeal: 'Grilled Portuguese sardines',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Portuguese',
    strInstructions:
      'STEP 1\r\n\r\nPut all of the ingredients, except the sardines, into a bowl and mix together with some seasoning. Pour into a baking dish, add the sardines and toss really well. Cover and chill for a few hours.\r\n\r\nSTEP 2\r\n\r\nHeat a BBQ or griddle pan until hot. Cook the sardines for 4-5 minutes on each side or until really caramelised and charred. Put onto a serving plate, drizzle with oil, sprinkle with a little more paprika and squeeze over the lemon wedges.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/lpd4wy1614347943.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=JYtMjKa6cdY',
    strIngredient1: 'Sardines',
    strIngredient2: 'Olive Oil',
    strIngredient3: 'Garlic',
    strIngredient4: 'Paprika',
    strIngredient5: 'Lemon',
    strIngredient6: 'Rosemary',
    strIngredient7: 'Red Chilli',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '8',
    strMeasure2: '2 tbs',
    strMeasure3: '3 cloves',
    strMeasure4: '1 tbs',
    strMeasure5: '1/2 ',
    strMeasure6: '4 sprigs',
    strMeasure7: '1',
    strMeasure8: ' ',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.olivemagazine.com/recipes/fish-and-seafood/grilled-portuguese-sardines/',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52773',
    strMeal: 'Honey Teriyaki Salmon',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Japanese',
    strInstructions:
      'Mix all the ingredients in the Honey Teriyaki Glaze together. Whisk to blend well. Combine the salmon and the Glaze together.\r\n\r\nHeat up a skillet on medium-low heat. Add the oil, Pan-fry the salmon on both sides until it’s completely cooked inside and the glaze thickens.\r\n\r\nGarnish with sesame and serve immediately.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg',
    strTags: 'Fish,Breakfast,DateNight',
    strYoutube: 'https://www.youtube.com/watch?v=4MpYuaJsvRw',
    strIngredient1: 'Salmon',
    strIngredient2: 'Olive oil',
    strIngredient3: 'Soy Sauce',
    strIngredient4: 'Sake',
    strIngredient5: 'Sesame Seed',
    strIngredient6: '',
    strIngredient7: '',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: undefined,
    strIngredient17: undefined,
    strIngredient18: undefined,
    strIngredient19: undefined,
    strIngredient20: undefined,
    strMeasure1: '1 lb',
    strMeasure2: '1 tablespoon',
    strMeasure3: '2 tablespoons',
    strMeasure4: '2 tablespoons',
    strMeasure5: '4 tablespoons',
    strMeasure6: '',
    strMeasure7: '',
    strMeasure8: '',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: undefined,
    strMeasure17: undefined,
    strMeasure18: undefined,
    strMeasure19: undefined,
    strMeasure20: undefined,
    strSource: undefined,
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52887',
    strMeal: 'Kedgeree',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'British',
    strInstructions:
      'For the rice, heat the oil in a large, lidded pan, add the onion, then gently fry for 5 mins until softened but not coloured. Add the spices, season with salt, then continue to fry until the mix start to go brown and fragrant; about 3 mins.\r\nAdd the rice and stir in well. Add 600ml water, stir, then bring to the boil. Reduce to a simmer, then cover for 10 mins. Take off the heat and leave to stand, covered, for 10-15 mins more. The rice will be perfectly cooked if you do not lift the lid before the end of the cooking.\r\nMeanwhile, put the haddock and bay leaves in a frying pan, cover with the milk, then poach for 10 mins until the flesh flakes. Remove from the milk, peel away the skin, then flake the flesh into thumbsize pieces. Place the eggs in a pan, cover with water, bring to the boil, then reduce to a simmer. Leave for 4½-5 mins, plunge into cold water, then peel and cut the eggs into quarters. Gently mix the fish, eggs, parsley, coriander and rice together in the pan. Serve hot, sprinkled with a few extra herbs.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=_Pw1I1-SItE',
    strIngredient1: 'Smoked Haddock',
    strIngredient2: 'Bay Leaves',
    strIngredient3: 'Milk',
    strIngredient4: 'Eggs',
    strIngredient5: 'Parsley',
    strIngredient6: 'Coriander',
    strIngredient7: 'Vegetable Oil',
    strIngredient8: 'Onion',
    strIngredient9: 'Coriander',
    strIngredient10: 'Curry Powder',
    strIngredient11: 'Rice',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '300g',
    strMeasure2: '2',
    strMeasure3: '300ml ',
    strMeasure4: '4',
    strMeasure5: 'Handful',
    strMeasure6: 'Handful',
    strMeasure7: '2 tbs',
    strMeasure8: '1 chopped',
    strMeasure9: '1 tsp ',
    strMeasure10: '2 tsp',
    strMeasure11: '300g',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbcgoodfood.com/recipes/10421/kedgeree',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52946',
    strMeal: 'Kung Po Prawns',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Chinese',
    strInstructions:
      'Mix the cornflour and 1 tbsp soy sauce, toss in the prawns and set aside for 10 mins. Stir the vinegar, remaining soy sauce, tomato purée, sugar and 2 tbsp water together to make a sauce.\r\n\r\nWhen you’re ready to cook, heat a large frying pan or wok until very hot, then add 1 tbsp oil. Fry the prawns until they are golden in places and have opened out– then tip them out of the pan.\r\n\r\nHeat the remaining oil and add the peanuts, chillies and water chestnuts. Stir-fry for 2 mins or until the peanuts start to colour, then add the ginger and garlic and fry for 1 more min. Tip in the prawns and sauce and simmer for 2 mins until thickened slightly. Serve with rice.',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1525873040.jpg',
    strTags: 'BBQ',
    strYoutube: 'https://www.youtube.com/watch?v=ysiuZm9FIxs',
    strIngredient1: 'Prawns',
    strIngredient2: 'Soy Sauce',
    strIngredient3: 'Tomato Puree',
    strIngredient4: 'Corn Flour',
    strIngredient5: 'Caster Sugar',
    strIngredient6: 'Sunflower Oil',
    strIngredient7: 'Peanuts',
    strIngredient8: 'Chilli',
    strIngredient9: 'Brown Sugar',
    strIngredient10: 'Garlic Clove',
    strIngredient11: 'Water Chestnut',
    strIngredient12: 'Ginger',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '400g',
    strMeasure2: '2 tbs',
    strMeasure3: '1 tsp ',
    strMeasure4: '1 tsp ',
    strMeasure5: '1 tsp ',
    strMeasure6: '1 tsp ',
    strMeasure7: '85g',
    strMeasure8: '3 Large',
    strMeasure9: '1 tbs',
    strMeasure10: '6 cloves',
    strMeasure11: '450g',
    strMeasure12: 'to taste',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbcgoodfood.com/recipes/1415664/kung-po-prawns',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52821',
    strMeal: 'Laksa King Prawn Noodles',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Malaysian',
    strInstructions:
      'Heat the oil in a medium saucepan and add the chilli. Cook for 1 min, then add the curry paste, stir and cook for 1 min more. Dissolve the stock cube in a large jug in 700ml boiling water, then pour into the pan and stir to combine. Tip in the coconut milk and bring to the boil.\r\nAdd the fish sauce and a little seasoning. Toss in the noodles and cook for a further 3-4 mins until softening. Squeeze in the lime juice, add the prawns and cook through until warm, about 2-3 mins. Scatter over some of the coriander.\r\nServe in bowls with the remaining coriander and lime wedges on top for squeezing over.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/rvypwy1503069308.jpg',
    strTags: 'Shellfish,Seafood',
    strYoutube: 'https://www.youtube.com/watch?v=OcarztU8cYo',
    strIngredient1: 'Olive Oil',
    strIngredient2: 'red chili',
    strIngredient3: 'Thai red curry paste',
    strIngredient4: 'vegetable stock cube',
    strIngredient5: 'coconut milk',
    strIngredient6: 'fish sauce',
    strIngredient7: 'rice noodles',
    strIngredient8: 'lime',
    strIngredient9: 'king prawns',
    strIngredient10: 'coriander',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 tbsp',
    strMeasure2: '1 finely sliced',
    strMeasure3: '2 ½ tbsp',
    strMeasure4: '1',
    strMeasure5: '400ml can',
    strMeasure6: '2 tsp',
    strMeasure7: '100g',
    strMeasure8: '2 juice of 1, the other halved',
    strMeasure9: '150g',
    strMeasure10: '½ small pack',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbcgoodfood.com/recipes/prawn-laksa-curry-bowl',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52777',
    strMeal: 'Mediterranean Pasta Salad',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Italian',
    strInstructions:
      'Bring a large saucepan of salted water to the boil\r\nAdd the pasta, stir once and cook for about 10 minutes or as directed on the packet.\r\nMeanwhile, wash the tomatoes and cut into quarters. Slice the olives. Wash the basil.\r\nPut the tomatoes into a salad bowl and tear the basil leaves over them. Add a tablespoon of olive oil and mix.\r\nWhen the pasta is ready, drain into a colander and run cold water over it to cool it quickly.\r\nToss the pasta into the salad bowl with the tomatoes and basil.\r\nAdd the sliced olives, drained mozzarella balls, and chunks of tuna. Mix well and let the salad rest for at least half an hour to allow the flavours to mingle.\r\nSprinkle the pasta with a generous grind of black pepper and drizzle with the remaining olive oil just before serving.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg',
    strTags: 'Pasta,Baking',
    strYoutube: 'https://www.youtube.com/watch?v=e52IL8zYmaE',
    strIngredient1: 'mozzarella balls',
    strIngredient2: 'baby plum tomatoes',
    strIngredient3: 'fresh basil',
    strIngredient4: 'farfalle',
    strIngredient5: 'extra virgin olive oil',
    strIngredient6: 'Green Olives',
    strIngredient7: 'tuna',
    strIngredient8: 'salt',
    strIngredient9: 'pepper',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: undefined,
    strIngredient17: undefined,
    strIngredient18: undefined,
    strIngredient19: undefined,
    strIngredient20: undefined,
    strMeasure1: '200 g',
    strMeasure2: '250 g',
    strMeasure3: '1  bunch',
    strMeasure4: '350 g',
    strMeasure5: '3  tablespoons',
    strMeasure6: '40 g',
    strMeasure7: '200 g',
    strMeasure8: 'to taste',
    strMeasure9: 'to taste',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: undefined,
    strMeasure17: undefined,
    strMeasure18: undefined,
    strMeasure19: undefined,
    strMeasure20: undefined,
    strSource: 'https://thelemonsqueezy.com/recipe/mediterranean-pasta-salad/',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '53048',
    strMeal: 'Mee goreng mamak',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Malaysian',
    strInstructions:
      'Heat oil in a pan at medium heat. Then, add peanuts, dried chilies, dried shrimps and dhal. Fry the aromatics until fragrant. Remove from pan and leave aside.\r\n\r\nBlend fried ingredients with tamarind paste and water until fine. Then, sauté the blended ingredients in oil heated over low heat. Continue cooking until the oil separates from the paste and turns a darker shade.\r\n\r\nSkin and cut potatoes into small chunks and boil them in a pot of water until knife-tender. Once ready, remove them from the pot and leave aside. Discard water.\r\n\r\nSlice onion and fried tofu, mince garlic, cut some cabbage and Chinese flowering cabbage (choi sam). Prepare prawn fritters and cut them. Boil noodles to soften them if bought dried. Also mix black soy sauce with water.\r\n\r\nTo fry one portion of mee goreng mamak, heat oil and add 1/4 of the following ingredients in this order: garlic, onion, paste. Sauté until fragrant. Optionally, add prawns.\r\n\r\nAdd in 1/4 amount of tofu, boiled potatoes, cabbage, Chinese flowering cabbage and prawn fritters. Sauté for another 30 seconds.\r\n\r\nAdd noodles to the wok. Add 3 tablespoons of dark soy sauce mixture. Mix evenly for the next 1 minute. Then, move the noodles to the side of the wok. Stir in an egg. Garnish with a slice of lime and slices of green chilies. To cook another plate of noodles, repeat from step 5 onwards.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/xquakq1619787532.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=pOJEmDBgtSk',
    strIngredient1: 'Peanuts',
    strIngredient2: 'Chilli',
    strIngredient3: 'Prawns',
    strIngredient4: 'Oil',
    strIngredient5: 'Water',
    strIngredient6: 'Tamarind Paste',
    strIngredient7: 'Potatoes',
    strIngredient8: 'Red Onions',
    strIngredient9: 'Garlic Clove',
    strIngredient10: 'Cabbage',
    strIngredient11: 'Chinese Broccoli',
    strIngredient12: 'Tofu',
    strIngredient13: 'Soy Sauce',
    strIngredient14: 'Noodles',
    strIngredient15: 'Egg',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '50g',
    strMeasure2: '15g',
    strMeasure3: '10g',
    strMeasure4: '5 tbs',
    strMeasure5: '750 ml ',
    strMeasure6: '1/2 tbs',
    strMeasure7: '250g',
    strMeasure8: '2',
    strMeasure9: '4',
    strMeasure10: '30g',
    strMeasure11: '30g',
    strMeasure12: '1',
    strMeasure13: '1 tbs',
    strMeasure14: '4',
    strMeasure15: '1',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.nyonyacooking.com/recipes/mee-goreng-mamak~BkTLRjTuX',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '53051',
    strMeal: 'Nasi lemak',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Malaysian',
    strInstructions:
      'In a medium saucepan over medium heat, stir together coconut milk, water, ground ginger, ginger root, salt, bay leaf, and rice. Cover, and bring to a boil. Reduce heat, and simmer for 20 to 30 minutes, or until done.\r\n\r\n Step 2\r\nPlace eggs in a saucepan, and cover with cold water. Bring water to a boil, and immediately remove from heat. Cover, and let eggs stand in hot water for 10 to 12 minutes. Remove eggs from hot water, cool, peel and slice in half. Slice cucumber.\r\n\r\n Step 3\r\nMeanwhile, in a large skillet or wok, heat 1 cup vegetable oil over medium-high heat. Stir in peanuts and cook briefly, until lightly browned. Remove peanuts with a slotted spoon and place on paper towels to soak up excess grease. Return skillet to stove. Stir in the contents of one package anchovies; cook briefly, turning, until crisp. Remove with a slotted spoon and place on paper towels. Discard oil. Wipe out skillet.\r\n\r\n Step 4\r\nHeat 2 tablespoons oil in the skillet. Stir in the onion, garlic, and shallots; cook until fragrant, about 1 or 2 minutes. Mix in the chile paste, and cook for 10 minutes, stirring occasionally. If the chile paste is too dry, add a small amount of water. Stir in remaining anchovies; cook for 5 minutes. Stir in salt, sugar, and tamarind juice; simmer until sauce is thick, about 5 minutes.\r\n\r\n Step 5\r\nServe the onion and garlic sauce over the warm rice, and top with peanuts, fried anchovies, cucumbers, and eggs.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/wai9bw1619788844.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=IUIs4C86Ilo',
    strIngredient1: 'Coconut Milk',
    strIngredient2: 'Water',
    strIngredient3: 'Ginger Paste',
    strIngredient4: 'Ginger',
    strIngredient5: 'Bay Leaf',
    strIngredient6: 'Rice',
    strIngredient7: 'Eggs',
    strIngredient8: 'Cucumber',
    strIngredient9: 'Peanuts',
    strIngredient10: 'Anchovy Fillet',
    strIngredient11: 'Vegetable Oil',
    strIngredient12: 'Onion',
    strIngredient13: 'Garlic',
    strIngredient14: 'Shallots',
    strIngredient15: 'Chilli Powder',
    strIngredient16: 'Anchovy Fillet',
    strIngredient17: 'Sugar',
    strIngredient18: 'Tamarind Paste',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2 cups ',
    strMeasure2: '2 cups ',
    strMeasure3: '1/4 tsp',
    strMeasure4: '1',
    strMeasure5: '1',
    strMeasure6: '2 cups ',
    strMeasure7: '4',
    strMeasure8: '1',
    strMeasure9: '1 cup ',
    strMeasure10: '4 oz ',
    strMeasure11: '2 tbs',
    strMeasure12: '1',
    strMeasure13: '3 cloves',
    strMeasure14: '3',
    strMeasure15: '2 tsp',
    strMeasure16: '4 oz ',
    strMeasure17: '3 tbs',
    strMeasure18: '1/3 cup',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://www.allrecipes.com/recipe/78938/malaysian-nasi-lemak/',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '53045',
    strMeal: 'Portuguese fish stew (Caldeirada de peixe)',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Portuguese',
    strInstructions:
      'STEP 1\r\n\r\nHeat a drizzle of oil in a large, deep-sided frying pan, and fry the onion and pepper on a medium heat until softened but not browned. Finely chop the coriander stalks (keep the leaves for later), and add to the pan with the chilli and chopped garlic. Fry for another few minutes. Add the wine, saffron and bay leaf and let it simmer until reduced by half.\r\n\r\nSTEP 2\r\n\r\nAdd the potatoes, tomatoes, and 300ml water and bring to a gentle boil. Break up the tomatoes with a spoon on the side of the pan and simmer for 20-25 minutes until the potatoes are just tender, and the tomatoes have broken down.\r\n\r\nSTEP 3\r\n\r\nSeason well, then gently push the fish into the sauce, and arrange the squid, prawns, clams and mussels on the surface. Put the lid on and cook for 6-8 minutes until the mussel and clam shells have opened, the prawns are cooked and the fish is flaky. Toast the bread, rub lightly with the halved garlic clove and drizzle with olive oil. Serve the stew scatted with chopped coriander leaves, and the toasts for dunking.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/do7zps1614349775.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=utv-GpSJypk',
    strIngredient1: 'Onions',
    strIngredient2: 'Red Pepper',
    strIngredient3: 'Coriander',
    strIngredient4: 'Red Chilli',
    strIngredient5: 'Garlic',
    strIngredient6: 'Dry White Wine',
    strIngredient7: 'Saffron',
    strIngredient8: 'Bay Leaf',
    strIngredient9: 'Potatoes',
    strIngredient10: 'Plum Tomatoes',
    strIngredient11: 'Cod',
    strIngredient12: 'Squid',
    strIngredient13: 'Tiger Prawns',
    strIngredient14: 'Clams',
    strIngredient15: 'Mussels',
    strIngredient16: 'Baguette',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2 finely chopped',
    strMeasure2: '1 Diced',
    strMeasure3: 'Small bunch',
    strMeasure4: '1 small',
    strMeasure5: '3 cloves',
    strMeasure6: '400ml',
    strMeasure7: 'Pinch',
    strMeasure8: '1',
    strMeasure9: '300g',
    strMeasure10: '400g',
    strMeasure11: '600g',
    strMeasure12: '300g',
    strMeasure13: '8',
    strMeasure14: '500g',
    strMeasure15: '500g',
    strMeasure16: '1 sliced',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.olivemagazine.com/recipes/one-pots/portuguese-fish-stew-caldeirada-de-peixe/',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52809',
    strMeal: 'Recheado Masala Fish',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Indian',
    strInstructions:
      "Soak all the spices, ginger, garlic, tamarind pulp and kashmiri chilies except oil in vinegar.\r\nAdd sugar and salt.\r\nAlso add turmeric powder.\r\nCombine all nicely and marinate for 35-40 mins.\r\nGrind the mixture until soft and smooth. Add more vinegar if required but ensure the paste has to be thick so add vinegar accordingly. If the masala paste is thin then it would not stick to the fish.\r\nRinse the fish slit from the center and give some incision from the top. You could see the fish below for clarity.\r\nNow stuff the paste into the center and into the incision. Coat the entire fish with this paste. Marinate the fish for 30 mins.\r\nPlace oil in a shallow pan, once oil is quite hot shallow fry the stuffed mackerels.\r\nFry until golden brown from both sides\r\nServe the recheado mackerels hot with salad, lime wedges, rice and curry.\r\nNotes\r\n1. Ensure the masala paste is thick else the result won't be good.\r\n2. If you aren't able to find kashmiri chilies then use bedgi chilies or kashmiri red chili powder.\r\n3. You could use white vinegar or coconut vinegar.\r\n4. Any left over paste could be stored in the fridge for future use.\r\n5. Cinnamon could be avoided as it's a strong spice used generally for meat or chicken.",
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/uwxusv1487344500.jpg',
    strTags: 'Fish,Spicy',
    strYoutube: 'https://www.youtube.com/watch?v=FXtCris37nE',
    strIngredient1: 'Mackerel',
    strIngredient2: 'Red Chili',
    strIngredient3: 'Ginger',
    strIngredient4: 'Garlic',
    strIngredient5: 'Pepper',
    strIngredient6: 'Cumin',
    strIngredient7: 'Turmeric',
    strIngredient8: 'Cinnamon stick',
    strIngredient9: 'Clove',
    strIngredient10: 'Cardamom',
    strIngredient11: 'Sugar',
    strIngredient12: 'Tamarind ball',
    strIngredient13: 'Vinegar',
    strIngredient14: 'Oil',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '4',
    strMeasure2: '18 dried',
    strMeasure3: '1 inch',
    strMeasure4: '8 cloves',
    strMeasure5: '1.5 tsp',
    strMeasure6: '1 tsp',
    strMeasure7: '½ tsp',
    strMeasure8: '',
    strMeasure9: '4',
    strMeasure10: '2',
    strMeasure11: '1 tbsp',
    strMeasure12: '2 marble sized',
    strMeasure13: '2.5 tbsp',
    strMeasure14: 'for frying',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'http://www.flavorsofmumbai.com/fish-recheado-masala-recipe/',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52960',
    strMeal: 'Salmon Avocado Salad',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'British',
    strInstructions:
      'Season the salmon, then rub with oil. Mix the dressing ingredients together. Halve, stone, peel and slice the avocados. Halve and quarter the cucumber lengthways, then cut into slices. Divide salad, avocado and cucumber between four plates, then drizzle with half the dressing.\r\n\r\nHeat a non-stick pan. Add the salmon and fry for 3-4 mins on each side until crisp but still moist inside. Put a salmon fillet on top of each salad and drizzle over the remaining dressing. Serve warm.',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1549542994.jpg',
    strTags: 'Paleo,Keto,LowCarbs,Salad,Alcoholic,Halloween,',
    strYoutube: 'https://www.youtube.com/watch?v=FJiu2S0Xap0',
    strIngredient1: 'Salmon',
    strIngredient2: 'Avocado',
    strIngredient3: 'Cucumber',
    strIngredient4: 'Spinach',
    strIngredient5: 'Mint',
    strIngredient6: 'Lime',
    strIngredient7: 'Honey',
    strIngredient8: 'Olive Oil',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '400g',
    strMeasure2: '3',
    strMeasure3: '1',
    strMeasure4: '400g',
    strMeasure5: '4 tbs',
    strMeasure6: 'zest and juice of 1',
    strMeasure7: '2 tsp',
    strMeasure8: '3 tbs',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource:
      'https://www.bbcgoodfood.com/recipes/4521/salmon-avocado-and-cucumber-salad',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52823',
    strMeal: 'Salmon Prawn Risotto',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Italian',
    strInstructions:
      'Melt the butter in a thick-based pan and gently cook the onion without colour until it is soft.\r\nAdd the rice and stir to coat all the grains in the butter\r\nAdd the wine and cook gently stirring until it is absorbed\r\nGradually add the hot stock, stirring until each addition is absorbed. Keep stirring until the rice is tender\r\nSeason with the lemon juice and zest, and pepper to taste. (there will probably be sufficient saltiness from the salmon to not need to add salt) Stir gently to heat through\r\nServe scattered with the Parmesan and seasonal vegetables.\r\nGrill the salmon and gently place onto the risotto with the prawns and asparagus',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg',
    strTags: 'Fish',
    strYoutube: 'https://www.youtube.com/watch?v=V2PMvBv52IE',
    strIngredient1: 'butter',
    strIngredient2: 'onion',
    strIngredient3: 'rice',
    strIngredient4: 'white wine',
    strIngredient5: 'vegetable stock',
    strIngredient6: 'lemon',
    strIngredient7: 'King Prawns',
    strIngredient8: 'salmon',
    strIngredient9: 'asparagus',
    strIngredient10: 'black pepper',
    strIngredient11: 'Parmesan',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '50g/2oz',
    strMeasure2: '1 finely chopped ',
    strMeasure3: '150g',
    strMeasure4: '125ml ',
    strMeasure5: '1 litre hot',
    strMeasure6: 'The juice and zest of one',
    strMeasure7: '240g large',
    strMeasure8: '150g',
    strMeasure9: '100g tips blanched briefly in boiling water',
    strMeasure10: 'ground',
    strMeasure11: '50g shavings',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource:
      'http://www.rangemaster.co.uk/rangemaster-owners/recipes-ideas-inspiration/recipes/mains/prawn-and-hot-smoked-salmon-risotto-with-asparagus',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52936',
    strMeal: 'Saltfish and Ackee',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Jamaican',
    strInstructions:
      'For the saltfish, soak the salt cod overnight, changing the water a couple of times.\r\nDrain, then put the cod in a large pan of fresh water and bring to the boil. Drain again, add fresh water and bring to the boil again.\r\nSimmer for about five minutes, or until cooked through, then drain and flake the fish into large pieces. Discard any skin or bones.\r\nFor the dumplings, mix the flour and suet with a pinch of salt and 250ml/9fl oz water to make a dough.\r\nWrap the mixture in clingfilm and leave in the fridge to rest.\r\nOpen the can of ackee, drain and rinse, then set aside.\r\nHeat a tablespoon of olive oil in a pan and fry the onion until softened but not brown.\r\nAdd the spices, seasoning, pepper sauce and sliced peppers and continue to fry until the peppers are tender.\r\nAdd the chopped tomatoes, then the salt cod and mix together. Lastly stir in the ackee very gently and leave to simmer until ready to serve.\r\nWhen you’re almost ready to eat, heat about 1cm/½in vegetable oil in a frying pan and heat until just smoking.\r\nShape the dumpling mix into plum-size balls and shallow-fry until golden-brown. (CAUTION: hot oil can be dangerous. Do not leave the pan unattended.)\r\nDrain the dumplings on kitchen paper and serve with the saltfish and ackee.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/vytypy1511883765.jpg',
    strTags: 'Speciality',
    strYoutube: 'https://www.youtube.com/watch?v=nbfNyZbdn2I',
    strIngredient1: 'Salt Cod',
    strIngredient2: 'Ackee',
    strIngredient3: 'Onion',
    strIngredient4: 'Paprika',
    strIngredient5: 'Curry Powder',
    strIngredient6: 'Jerusalem Artichokes',
    strIngredient7: 'Hotsauce',
    strIngredient8: 'Red Pepper',
    strIngredient9: 'Yellow Pepper',
    strIngredient10: 'Tomatoes',
    strIngredient11: 'Salt',
    strIngredient12: 'Pepper',
    strIngredient13: 'Self-raising Flour',
    strIngredient14: 'Suet',
    strIngredient15: 'Salt',
    strIngredient16: 'Olive Oil',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '450g',
    strMeasure2: '400g',
    strMeasure3: '1 chopped',
    strMeasure4: '1 tsp ',
    strMeasure5: '2 tsp',
    strMeasure6: '2 tsp',
    strMeasure7: '1 tsp ',
    strMeasure8: '1 sliced',
    strMeasure9: '1 sliced',
    strMeasure10: '200g',
    strMeasure11: 'to taste',
    strMeasure12: 'to taste',
    strMeasure13: '250g',
    strMeasure14: '30g',
    strMeasure15: 'pinch',
    strMeasure16: 'for frying',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbc.co.uk/food/recipes/saltfish__ackee_with_64803',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52836',
    strMeal: 'Seafood fideuà',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Spanish',
    strInstructions:
      'Boil the kettle. Empty the mussels into a colander and run under cold water. Throw away any with broken shells. Pick through the shells, tapping each one on the side of the sink – they should be closed or should slowly close when tapped – if they stay open, throw them away. If any of the shells still have barnacles or stringy beards attached, pull them off with a cutlery knife and rinse the shells well. Keep in the colander, covered with a cold, damp cloth, until you’re ready to cook. Peel the prawn shells on the body section only – leave the heads and tails intact. Score down the backs and pull out any gritty entrails. Chill until you’re ready to cook.\r\nPut the saffron in a small cup, cover with 50ml kettle-hot water and set aside for 10 mins. If using vermicelli, put in a bowl and crush to little pieces (about 1cm long) with your hands.\r\nHeat the oil in a large frying pan with at least a 3cm lip, or a 40cm paella pan. Add the onion and stir around the pan for 5 mins until soft. Add the garlic and cook for 1 min more, then tip in the vermicelli and cook for 5 mins, stirring from time to time, until the vermicelli is toasted brown. Stir in the paprika.\r\nKeeping the heat moderate, stir through the monkfish, squid and saffron with its water, seasoning well. Spread the ingredients out in an even layer, then pour over the hot stock and scatter the tomatoes on top. Bring to a simmer, then cover the whole dish with a tight-fitting lid (or foil). Turn the heat to medium and cook for 6 mins.\r\nUncover and stir to incorporate the dry top layer of pasta. Push the mussels into the pasta so the hinges are buried in the bottom of the dish, and they stand straight up. Arrange the prawns on top, cover tightly and cook for another 6 mins or until the mussels are open, the prawns are pink and the pasta is cooked through. Leave to simmer for another 2-3 mins to cook off most of the remaining liquid (leave a little in the pan to prevent the pasta from sticking together). Allow to sit for 2-3 mins, then squeeze over the lemon juice and arrange the wedges on top. Scatter with parsley before serving.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/wqqvyq1511179730.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=itsFEc8W468',
    strIngredient1: 'Mussels',
    strIngredient2: 'Prawns',
    strIngredient3: 'Saffron',
    strIngredient4: 'Vermicelli',
    strIngredient5: 'Olive Oil',
    strIngredient6: 'Onions',
    strIngredient7: 'Garlic',
    strIngredient8: 'Paprika',
    strIngredient9: 'Monkfish',
    strIngredient10: 'Baby Squid',
    strIngredient11: 'Fish Stock',
    strIngredient12: 'Tomatoes',
    strIngredient13: 'Lemon',
    strIngredient14: 'Parsley',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '400g',
    strMeasure2: '8',
    strMeasure3: '2 pinches',
    strMeasure4: '350g',
    strMeasure5: '5 tblsp ',
    strMeasure6: '1 large',
    strMeasure7: '3 cloves',
    strMeasure8: '2 tbs',
    strMeasure9: '1 tail',
    strMeasure10: '4',
    strMeasure11: '650ml',
    strMeasure12: '2 large',
    strMeasure13: 'Juice of 1',
    strMeasure14: 'Topping',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbcgoodfood.com/recipes/seafood-fideua-paella',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52953',
    strMeal: 'Shrimp Chow Fun',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Chinese',
    strInstructions:
      "STEP 1 - SOAK THE RICE NOODLES\r\nSoak the rice noodles overnight untill they are soft\r\nSTEP 2 - BOIL THE RICE NOODLES\r\nBoil the noodles for 10-15 minutes and then rinse with cold water to stop the cooking process of the noodles.\r\nSTEP 3 -MARINATING THE SHRIMP\r\nIn a bowl add the shrimp, egg, 1 pinch of white pepper, 1 Teaspoon of sesame seed oil, 1 Tablespoon corn starch and 1 tablespoon of oil\r\nMix together well\r\nSTEP 4 - STIR FRY\r\nIn a wok add 2 Tablespoons of oil, shrimp and stir fry them until it is golden brown\r\nSet the shrimp aside\r\nAdd 1 Tablespoon of oil to the work and then add minced garlic, ginger and all of the vegetables.\r\nAdd the noodles to the wok\r\nNext add sherry cooking wine, oyster sauce, sugar, vinegar, sesame seed oil, 1 pinch white pepper, and soy sauce\r\nAdd back in the shrimp\r\nTo thicken the sauce, whisk together 1 Tablespoon of corn starch and 2 Tablespoon of water in a bowl and slowly add to your stir-fry until it's the right thickness.",
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1529445434.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=wzaTcpoFEaY',
    strIngredient1: 'Rice Stick Noodles',
    strIngredient2: 'Prawns',
    strIngredient3: 'Egg',
    strIngredient4: 'Pepper',
    strIngredient5: 'Sesame Seed Oil',
    strIngredient6: 'Cornstarch',
    strIngredient7: 'Oil',
    strIngredient8: 'Minced Garlic',
    strIngredient9: 'Ginger',
    strIngredient10: 'Onion',
    strIngredient11: 'Bean Sprouts',
    strIngredient12: 'Spring Onions',
    strIngredient13: 'Cooking wine',
    strIngredient14: 'Oyster Sauce',
    strIngredient15: 'Sugar',
    strIngredient16: 'Vinegar',
    strIngredient17: 'Soy Sauce',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1/2 bag',
    strMeasure2: '8 oz ',
    strMeasure3: '1/2 ',
    strMeasure4: 'pinch',
    strMeasure5: '2 tsp',
    strMeasure6: '2 tbs',
    strMeasure7: '4 tbs',
    strMeasure8: '1 tsp ',
    strMeasure9: '1 tsp ',
    strMeasure10: '1/2 cup ',
    strMeasure11: '1 cup ',
    strMeasure12: '1/2 cup ',
    strMeasure13: '1 tbs',
    strMeasure14: '1 tbs',
    strMeasure15: '1/2 tbs',
    strMeasure16: '1/2 tbs',
    strMeasure17: '1 tbs',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://sueandgambo.com/pages/shrimp-chow-fun',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '53023',
    strMeal: 'Sledz w Oleju (Polish Herrings)',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Polish',
    strInstructions:
      'Soak herring in cold water for at least 1 hour. If very salty, repeat, changing the water each time.\r\n\r\nDrain thoroughly and slice herring into bite-size pieces.\r\n\r\nPlace in a jar large enough to accommodate the pieces and cover with oil, allspice, peppercorns, and bay leaf. Close the jar.\r\n\r\nRefrigerate for 2 to 3 days before eating. This will keep refrigerated up to 2 weeks.\r\n\r\nServe with finely chopped onion or onion slices, lemon, and parsley or dill.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/7ttta31593350374.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=v6I3GZlBkOM',
    strIngredient1: 'Herring',
    strIngredient2: 'Onion',
    strIngredient3: 'Olive Oil',
    strIngredient4: 'Allspice',
    strIngredient5: 'Pepper',
    strIngredient6: 'Bay Leaf',
    strIngredient7: '',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '8',
    strMeasure2: '1 sliced',
    strMeasure3: '1/2 cup ',
    strMeasure4: '1 tsp ',
    strMeasure5: '1 tsp ',
    strMeasure6: '1',
    strMeasure7: ' ',
    strMeasure8: ' ',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.thespruceeats.com/polish-herrings-in-oil-recipe-1135618',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '53040',
    strMeal: 'Spring onion and prawn empanadas',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Portuguese',
    strInstructions:
      'STEP 1\r\n\r\nTo make the dough, rub the butter into the flour and then add the egg white and half the yolk (keep the rest), vinegar, a pinch of salt and enough cold water to make a soft dough. Knead on a floured surface until smooth and then wrap and rest for 30 minutes.\r\n\r\nSTEP 2\r\n\r\nHeat the oven to 180c/fan 160c/gas 4. Trim the green ends of the spring onions and then finely slice the rest. Heat a little oil in a pan and fry them gently until soft but not browned. Add the chilli and garlic, stir and then add the prawns and cook until they are opaque. Season well. Scoop out the prawns and bubble the juices until they thicken, then add back the prawns.\r\n\r\nSTEP 3\r\n\r\nDivide the empanada dough into eight balls and roll out to thin circles on a floured surface. Put some filling on one half of the dough, sprinkle the feta on top and fold the other half over. Trim the edge and then fold and crimp the dough together so the empanada is tightly sealed, put it on an oiled baking sheet either on its side or sitting on its un-crimped edge like a cornish pasty. Repeat with the remaining dough and mixture. Mix the leftover egg yolk with a splash of water and brush the top of the empanadas.\r\n\r\nSTEP 4\r\n\r\nBake for 30 minutes or until golden and slightly crisp around the edges.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/1c5oso1614347493.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=Q24haJU-1dI',
    strIngredient1: 'Spring Onions',
    strIngredient2: 'Olive Oil',
    strIngredient3: 'Red Chilli',
    strIngredient4: 'Garlic',
    strIngredient5: 'Prawns',
    strIngredient6: 'Feta',
    strIngredient7: 'Butter',
    strIngredient8: 'Plain Flour',
    strIngredient9: 'Egg',
    strIngredient10: 'White Wine Vinegar',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1  bunch',
    strMeasure2: 'Dash',
    strMeasure3: '1 finely sliced',
    strMeasure4: '1 clove',
    strMeasure5: '350g',
    strMeasure6: '75g',
    strMeasure7: '15g',
    strMeasure8: '250g',
    strMeasure9: '1 Seperated',
    strMeasure10: '1/2 tsp',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.olivemagazine.com/recipes/fish-and-seafood/spring-onion-and-prawn-empanadas/',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '53065',
    strMeal: 'Sushi',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Japanese',
    strInstructions:
      'STEP 1\r\nTO MAKE SUSHI ROLLS: Pat out some rice. Lay a nori sheet on the mat, shiny-side down. Dip your hands in the vinegared water, then pat handfuls of rice on top in a 1cm thick layer, leaving the furthest edge from you clear.\r\n\r\nSTEP 2\r\nSpread over some Japanese mayonnaise. Use a spoon to spread out a thin layer of mayonnaise down the middle of the rice.\r\n\r\nSTEP 3\r\nAdd the filling. Get your child to top the mayonnaise with a line of their favourite fillings – here we’ve used tuna and cucumber.\r\n\r\nSTEP 4\r\nRoll it up. Lift the edge of the mat over the rice, applying a little pressure to keep everything in a tight roll.\r\n\r\nSTEP 5\r\nStick down the sides like a stamp. When you get to the edge without any rice, brush with a little water and continue to roll into a tight roll.\r\n\r\nSTEP 6\r\nWrap in cling film. Remove the mat and roll tightly in cling film before a grown-up cuts the sushi into thick slices, then unravel the cling film.\r\n\r\nSTEP 7\r\nTO MAKE PRESSED SUSHI: Layer over some smoked salmon. Line a loaf tin with cling film, then place a thin layer of smoked salmon inside on top of the cling film.\r\n\r\nSTEP 8\r\nCover with rice and press down. Press about 3cm of rice over the fish, fold the cling film over and press down as much as you can, using another tin if you have one.\r\n\r\nSTEP 9\r\nTip it out like a sandcastle. Turn block of sushi onto a chopping board. Get a grown-up to cut into fingers, then remove the cling film.\r\n\r\nSTEP 10\r\nTO MAKE SUSHI BALLS: Choose your topping. Get a small square of cling film and place a topping, like half a prawn or a small piece of smoked salmon, on it. Use damp hands to roll walnut-sized balls of rice and place on the topping.\r\n\r\nSTEP 11\r\nMake into tight balls. Bring the corners of the cling film together and tighten into balls by twisting it up, then unwrap and serve.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=ub68OxEypaY',
    strIngredient1: 'Sushi Rice',
    strIngredient2: 'Rice wine',
    strIngredient3: 'Caster Sugar',
    strIngredient4: 'Mayonnaise',
    strIngredient5: 'Rice wine',
    strIngredient6: 'Soy Sauce',
    strIngredient7: 'Cucumber',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '300ml ',
    strMeasure2: '100ml',
    strMeasure3: '2 tbs',
    strMeasure4: '3 tbs',
    strMeasure5: '1 tbs',
    strMeasure6: '1 tbs',
    strMeasure7: '1',
    strMeasure8: ' ',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://www.bbcgoodfood.com/recipes/simple-sushi',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52882',
    strMeal: 'Three Fish Pie',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'British',
    strInstructions:
      'Preheat the oven to 200C/400F/Gas 6 (180C fan).\r\nPut the potatoes into a saucepan of cold salted water. Bring up to the boil and simmer until completely tender. Drain well and then mash with the butter and milk. Add pepper and taste to check the seasoning. Add salt and more pepper if necessary.\r\nFor the fish filling, melt the butter in a saucepan, add the leeks and stir over the heat. Cover with a lid and simmer gently for 10 minutes, or until soft. Measure the flour into a small bowl. Add the wine and whisk together until smooth.\r\nAdd the milk to the leeks, bring to the boil and then add the wine mixture. Stir briskly until thickened. Season and add the parsley and fish. Stir over the heat for two minutes, then spoon into an ovenproof casserole. Scatter over the eggs. Allow to cool until firm.\r\nSpoon the mashed potatoes over the fish mixture and mark with a fork. Sprinkle with cheese.\r\nBake for 30-40 minutes, or until lightly golden-brown on top and bubbling around the edges.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/spswqs1511558697.jpg',
    strTags: 'Fish,Seafood,Dairy,Pie',
    strYoutube: 'https://www.youtube.com/watch?v=Ds1Jb8H5Sg8',
    strIngredient1: 'Potatoes',
    strIngredient2: 'Butter',
    strIngredient3: 'Milk',
    strIngredient4: 'Gruyère',
    strIngredient5: 'Butter',
    strIngredient6: 'Leek',
    strIngredient7: 'Plain Flour',
    strIngredient8: 'White Wine',
    strIngredient9: 'Milk',
    strIngredient10: 'Parsley',
    strIngredient11: 'Salmon',
    strIngredient12: 'Haddock',
    strIngredient13: 'Smoked Haddock',
    strIngredient14: 'Eggs',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1kg',
    strMeasure2: 'Knob',
    strMeasure3: 'Dash',
    strMeasure4: '50g',
    strMeasure5: '75g',
    strMeasure6: '2 sliced',
    strMeasure7: '75g',
    strMeasure8: '150ml',
    strMeasure9: '568ml',
    strMeasure10: '2 tbs chopped',
    strMeasure11: '250g',
    strMeasure12: '250g',
    strMeasure13: '250g',
    strMeasure14: '6',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbc.co.uk/food/recipes/three_fish_pie_58875',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52975',
    strMeal: 'Tuna and Egg Briks',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'Tunisian',
    strInstructions:
      'Heat 2 tsp of the oil in a large saucepan and cook the spring onions over a low heat for 3 minutes or until beginning to soften. Add the spinach, cover with a tight-fitting lid and cook for a further 2–3 minutes or until tender and wilted, stirring once or twice. Tip the mixture into a sieve or colander and leave to drain and cool.\r\nUsing a saucer as a guide, cut out 24 rounds about 12.5 cm (5 in) in diameter from the filo pastry, cutting 6 rounds from each sheet. Stack the filo rounds in a pile, then cover with cling film to prevent them from drying out.\r\nWhen the spinach mixture is cool, squeeze out as much excess liquid as possible, then transfer to a bowl. Add the tuna, eggs, hot pepper sauce, and salt and pepper to taste. Mix well.\r\nPreheat the oven to 200°C (400°F, gas mark 6). Take one filo round and very lightly brush with some of the remaining oil. Top with a second round and brush with a little oil, then place a third round on top and brush with oil.\r\nPlace a heaped tbsp of the filling in the middle of the round, then fold the pastry over to make a half-moon shape. Fold in the edges, twisting them to seal, and place on a non-stick baking sheet. Repeat with the remaining pastry and filling to make 8 briks in all.\r\nLightly brush the briks with the remaining oil. Bake for 12–15 minutes or until the pastry is crisp and golden brown.\r\nMeanwhile, combine the tomatoes and cucumber in a bowl and sprinkle with the lemon juice and seasoning to taste. Serve the briks hot with this salad and the chutney.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/2dsltq1560461468.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=C5n1fN8TGHs',
    strIngredient1: 'Olive Oil',
    strIngredient2: 'Spring Onions',
    strIngredient3: 'Spinach',
    strIngredient4: 'Filo Pastry',
    strIngredient5: 'Tuna',
    strIngredient6: 'Eggs',
    strIngredient7: 'Hotsauce',
    strIngredient8: 'Tomatoes',
    strIngredient9: 'Cucumber',
    strIngredient10: 'Lemon Juice',
    strIngredient11: 'Apricot Jam',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2 tbs',
    strMeasure2: '8',
    strMeasure3: '200g',
    strMeasure4: '4',
    strMeasure5: '1 can ',
    strMeasure6: '2',
    strMeasure7: 'Dash',
    strMeasure8: '4 Chopped',
    strMeasure9: '1/4 ',
    strMeasure10: '1 tbs',
    strMeasure11: '4 tbs',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'http://allrecipes.co.uk/recipe/3096/tunisian-tuna-and-egg-briks.aspx',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
  {
    idMeal: '52852',
    strMeal: 'Tuna Nicoise',
    strDrinkAlternate: undefined,
    strCategory: 'Seafood',
    strArea: 'French',
    strInstructions:
      'Heat oven to 200C/fan 180C/gas 6. Toss the potatoes with 2 tsp oil and some seasoning. Tip onto a large baking tray, then roast for 20 mins, stirring halfway, until crisp, golden and cooked through.\r\nMeanwhile, put eggs in a small pan of water, bring to the boil, then simmer for 8-10 mins, depending on how you like them cooked. Plunge into a bowl of cold water to cool for a few mins. Peel away the shells, then cut into halves.\r\nIn a large salad bowl, whisk together the remaining oil, red wine vinegar, capers and chopped tomatoes. Season, tip in the onion, spinach, tuna and potatoes, then gently toss together. Top with the eggs, then serve straight away.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/yypwwq1511304979.jpg',
    strTags: undefined,
    strYoutube: 'https://www.youtube.com/watch?v=3_UAxkx0u6U',
    strIngredient1: 'Potatoes',
    strIngredient2: 'Olive Oil',
    strIngredient3: 'Eggs',
    strIngredient4: 'Red Wine Vinegar',
    strIngredient5: 'Capers',
    strIngredient6: 'Sunflower Oil',
    strIngredient7: 'Red Onions',
    strIngredient8: 'Spinach',
    strIngredient9: 'Tuna',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '450g',
    strMeasure2: '2 tblsp ',
    strMeasure3: '4',
    strMeasure4: '1 tbls',
    strMeasure5: '2 tblsp ',
    strMeasure6: '50g',
    strMeasure7: '½',
    strMeasure8: '100g ',
    strMeasure9: '400g',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbcgoodfood.com/recipes/9529/winter-tuna-nioise',
    strImageSource: undefined,
    strCreativeCommonsConfirmed: undefined,
    dateModified: undefined,
  },
];
